#!/bin/bash

##Instalação do Node.JS
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt install nodejs -y nodejs

##Instalação do Angular CLI
sudo npm install -g @angular/cli
